#!/bin/bash
# SXHKD FOR GLOBAL AND BSPWM KEYBINDS
pgrep -x sxhkd || sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/bspwm" &
# RUN PICOM IF NOT RUNNING
pgrep -x picom || picom --experimental-backends &

# PYWAL COLORS
. "$HOME/.cache/wal/colors.sh"

# WORKSPACE NAMES
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# WINDOW DECORATIONS
bspc config border_width            2
bspc config window_gap              12
bspc config normal_border_color     "$color0"
bspc config active_border_color     "$color0"
bspc config focused_border_color    "$color1"

# WINDOW MANAGER OPTIONS
bspc config pointer_modifier        mod1
bspc config split_ratio             0.55
#bspc config automatic_scheme        longest_side
bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config single_monocle          true

# APPLICATION RULES
bspc rule -a "Pavucontrol" state=floating
bspc rule -a "imv" state=floating
bspc rule -a "Wpg" state=floating
bspc rule -a "Nvidia-settings" state=floating
bspc rule -a "*:*:Picture in picture" state=floating

# LAUNCH POLYBAR
# (LAUNCH YOUR BARS AFTER WORKSPACE NAMES ARE SET)
. "$HOME/.scripts/polybar.sh" bspwm
