#!/bin/sh
# SXHKD FOR GLOBAL AND BSPWM KEYBINDS
pgrep -x sxhkd || sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/bspwm" &
# RUN PICOM IF NOT RUNNING
pgrep -x picom || picom --experimental-backends &

# WORKSPACES
bspc monitor DisplayPort-0 -d 1 2 3 4 5
#bspc monitor HDMI-1 -d 6 7 8 9 10

bspc config border_width            3
# WINDOW DECORATIONS
bspc config window_gap              10
bspc config normal_border_color     "$color0"
bspc config active_border_color     "$color0"
bspc config focused_border_color    "$color1"

# WINDOW MANAGER OPTIONS
bspc config pointer_modifier mod1
bspc config split_ratio 0.5
bspc config automatic_scheme alternate
bspc config focus_follows_pointer true
bspc config borderless_monocle true
bspc config single_monocle true
bspc config -m DisplayPort-0 bottom_padding 50

# APPLICATION RULES
bspc rule -a "Pavucontrol" state=floating
bspc rule -a "imv" state=floating
bspc rule -a "feh" state=floating
bspc rule -a "Wpg" state=floating
bspc rule -a "MEGAsync" state=floating
bspc rule -a "mpv" state=floating
bspc rule -a "Nvidia-settings" state=floating
bspc rule -a "OpenTabletDriver.UX.Gtk" state=floating
bspc rule -a "*:*:Picture in picture" state=floating

pgrep -x xfce4-panel || xfce4-panel --disable-wm-check &
