#!/bin/bash
# SXHKD FOR GLOBAL AND BSPWM KEYBINDS
pgrep -x sxhkd || sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" "$HOME/.config/sxhkd/berry" &
# RUN PICOM IF NOT RUNNING
pgrep -x picom || picom --experimental-backends &

berryc border_width 0
berryc inner_border_width 2

berryc draw_text "true"
berryc title_height 30

berryc edge_gap 10 66 10 10

berryc smart_place "true"
berryc decorate_new "true"
berryc edge_lock   "true"

pgrep -x eww || eww open bar &
